# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  clean: true
  persistCredentials: true

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- powershell: |
   git switch -c master
   git config --global user.email "regobs@nve.no"
   git config --global user.name "Azure DevOps Pipeline"
  displayName: 'PowerShell Script'
- task: Npm@1
  displayName: 'npm version patch'
  inputs:
    command: custom
    verbose: false
    customCommand: 'version patch --force -m "[skip ci] AzurePipeline Release (CI)"'

- script: |
   git push --follow-tags origin master   
  displayName: 'Git push new package version and tags'

- task: CopyFiles@2
  inputs:
    Contents: |
      package.json
      api/**
      app/**
      helptexts/**
      kdvelements/**
      web/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: GitHubRelease@1
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: 'Github Service Connection'
    releaseNotesSource: inline
    releaseNotesInline: 'Azure Pipelines CI Release'

