project_identifier: varsom-regobs
base_path: .
preserve_hierarchy: true
files:
  - source: /app/native-dialogs/en.json
    translation: /app/native-dialogs/%two_letters_code%.%file_extension%
    type: json
  - source: /app/i18n/en.json
    translation: /app/i18n/%two_letters_code%.%file_extension%
    type: json
  - source: /web/en.json
    translation: /web/%two_letters_code%.%file_extension%
    type: json
